import { db } from "./db";
import { clients, useCases, marketplaceUseCases } from "@shared/schema";

const seedData = async () => {
  console.log("Seeding database...");

  // Create a sample podiatry client
  const [podiatryClient] = await db.insert(clients).values({
    name: "Sunshine Podiatry Clinic",
    industryVertical: "Podiatry",
  }).returning();

  console.log("Created client:", podiatryClient.name);

  // Create podiatry use cases
  const podiatryUseCases = [
    {
      clientId: podiatryClient.id,
      title: "Upload email list into Mailchimp",
      industryVertical: "Podiatry",
      department: "Marketing",
      level: 1,
      status: "Live" as const,
      riskRating: "Low" as const,
      piiFlag: true,
      dataFlow: "VendorTools" as const,
      humanInLoop: "Required" as const,
      storyToday: "Currently, the marketing assistant manually exports patient email addresses from the practice management system, removes duplicates in Excel, and uploads them to Mailchimp. This takes about 30 minutes each week and is prone to formatting errors.",
      storyFuture: "1. Staff triggers the sync from practice management system\n2. Tool exports and formats email addresses\n3. Duplicates are automatically removed\n4. Clean list is uploaded to Mailchimp\n5. Staff reviews the upload confirmation",
      controls: ["Redact patient health information", "Only email addresses exported", "Staff approval before upload", "Audit log maintained"],
      tools: ["Mailchimp", "Excel", "Zapier"],
      baselineMinutesPerRun: 30,
      frequencyPerWeek: 1,
      roiTimeSavedMinutesPerWeek: 25,
      roiDollarsPerMonth: 125,
      priorityOrder: 1,
    },
    {
      clientId: podiatryClient.id,
      title: "Generate and schedule Facebook posts",
      industryVertical: "Podiatry",
      department: "Marketing",
      level: 2,
      status: "Building" as const,
      riskRating: "Low" as const,
      piiFlag: false,
      dataFlow: "VendorTools" as const,
      humanInLoop: "Optional" as const,
      storyToday: "The office manager spends 2 hours weekly creating social media posts, finding stock images, and scheduling them on Facebook. Content often focuses on foot health tips and clinic promotions.",
      storyFuture: "1. Weekly content calendar is auto-generated based on templates\n2. Relevant stock images are selected automatically\n3. Posts are scheduled for optimal engagement times\n4. Staff receives preview notification for approval\n5. Posts go live after approval timeout",
      controls: ["No medical advice in posts", "Brand guidelines enforced", "Review queue for staff oversight", "No patient photos without consent"],
      tools: ["Meta Business Suite", "Canva", "Buffer"],
      baselineMinutesPerRun: 120,
      frequencyPerWeek: 1,
      roiTimeSavedMinutesPerWeek: 100,
      roiDollarsPerMonth: 500,
      priorityOrder: 2,
    },
    {
      clientId: podiatryClient.id,
      title: "Instagram DM auto-responder",
      industryVertical: "Podiatry",
      department: "Front Desk",
      level: 3,
      status: "Proposed" as const,
      riskRating: "High" as const,
      piiFlag: true,
      dataFlow: "CloudLLM" as const,
      humanInLoop: "Required" as const,
      storyToday: "Front desk staff manually responds to Instagram DMs during business hours. Many messages are simple appointment inquiries or location questions. Staff spends 45 minutes daily on these messages.",
      storyFuture: "1. AI monitors incoming Instagram DMs\n2. Message intent is classified automatically\n3. Simple queries (hours, location, services) get instant responses\n4. Appointment requests are routed to booking system\n5. Medical questions are escalated to human with disclaimer\n6. All conversations logged for audit",
      controls: ["No diagnosis or medical advice", "Immediate escalation for health questions", "Human review for appointment confirmations", "Clear bot disclosure in messages", "PII redacted before LLM processing", "Response templates pre-approved by clinic"],
      tools: ["Instagram API", "ChatGPT", "Zapier", "Practice Management System"],
      baselineMinutesPerRun: 45,
      frequencyPerWeek: 5,
      roiTimeSavedMinutesPerWeek: 180,
      roiDollarsPerMonth: 900,
      priorityOrder: 3,
    },
    {
      clientId: podiatryClient.id,
      title: "Patient appointment reminder calls",
      industryVertical: "Podiatry",
      department: "Admin",
      level: 2,
      status: "Live" as const,
      riskRating: "Medium" as const,
      piiFlag: true,
      dataFlow: "VendorTools" as const,
      humanInLoop: "None" as const,
      storyToday: "Admin staff manually calls patients 24 hours before their appointment to confirm. This takes about 3 hours per day and many calls go to voicemail.",
      storyFuture: "1. System pulls next-day appointments automatically\n2. Personalized reminder messages are generated\n3. Automated calls/SMS sent to patients\n4. Responses are logged and synced to calendar\n5. No-confirms are flagged for staff follow-up",
      controls: ["HIPAA-compliant messaging", "Opt-out respected", "No appointment details in voicemail", "Staff notified of cancellations"],
      tools: ["Twilio", "Practice Management System", "Google Calendar"],
      baselineMinutesPerRun: 180,
      frequencyPerWeek: 5,
      roiTimeSavedMinutesPerWeek: 750,
      roiDollarsPerMonth: 3750,
      priorityOrder: 4,
    },
    {
      clientId: podiatryClient.id,
      title: "Patient intake form digitization",
      industryVertical: "Podiatry",
      department: "Admin",
      level: 1,
      status: "Approved" as const,
      riskRating: "High" as const,
      piiFlag: true,
      dataFlow: "LocalOnly" as const,
      humanInLoop: "Required" as const,
      storyToday: "New patients fill out paper forms in the waiting room. Staff then manually enters this information into the practice management system, which takes 15 minutes per patient.",
      storyFuture: "1. Patient receives digital form link before appointment\n2. Form is completed online with validation\n3. Data is reviewed by staff for accuracy\n4. Approved data syncs to practice management system\n5. Patient signs consent digitally",
      controls: ["HIPAA-compliant storage", "Data encryption at rest", "Staff verification required", "Audit trail for all access", "Patient consent obtained"],
      tools: ["JotForm", "Practice Management System"],
      baselineMinutesPerRun: 15,
      frequencyPerWeek: 20,
      roiTimeSavedMinutesPerWeek: 200,
      roiDollarsPerMonth: 1000,
      priorityOrder: 5,
    },
  ];

  for (const useCase of podiatryUseCases) {
    await db.insert(useCases).values(useCase);
    console.log("Created use case:", useCase.title);
  }

  // Seed marketplace use cases
  console.log("\nSeeding marketplace use cases...");
  
  const marketplaceTemplates = [
    {
      title: "Automated Appointment Reminders",
      description: "Send automated SMS/email reminders to patients 24-48 hours before appointments to reduce no-shows.",
      industryVertical: "Healthcare",
      scope: "Communications",
      department: "Admin",
      level: 2,
      goals: ["Efficiency", "Customer Retention", "Fewer Phone Calls"],
      riskRating: "Medium" as const,
      piiFlag: true,
      dataFlow: "VendorTools" as const,
      humanInLoop: "Optional" as const,
      storyToday: "Staff manually calls each patient the day before their appointment, spending hours on the phone leaving voicemails.",
      storyFuture: "1. System automatically pulls next-day appointments\n2. Personalized reminder messages are generated\n3. SMS/Email sent to patients automatically\n4. Confirmations and cancellations logged\n5. Staff notified of any issues",
      controls: ["HIPAA-compliant messaging", "Opt-out option included", "No sensitive details in messages", "Audit trail maintained"],
      tools: ["Twilio", "Practice Management System"],
      baselineMinutesPerRun: 120,
      frequencyPerWeek: 5,
      roiTimeSavedMinutesPerWeek: 500,
      roiDollarsPerMonth: 2500,
    },
    {
      title: "Social Media Content Scheduler",
      description: "Automatically generate and schedule engaging social media posts to maintain consistent online presence.",
      industryVertical: "Healthcare",
      scope: "Social",
      department: "Marketing",
      level: 2,
      goals: ["Leads", "Education", "Revenue Growth"],
      riskRating: "Low" as const,
      piiFlag: false,
      dataFlow: "VendorTools" as const,
      humanInLoop: "Optional" as const,
      storyToday: "Marketing team spends hours each week creating, designing, and scheduling social media content manually.",
      storyFuture: "1. Content calendar auto-generated from templates\n2. Stock images and graphics selected\n3. Posts scheduled for optimal times\n4. Staff reviews before publishing\n5. Analytics tracked automatically",
      controls: ["Brand guidelines enforced", "No medical advice", "Staff approval queue", "Content moderation"],
      tools: ["Buffer", "Canva", "Meta Business Suite"],
      baselineMinutesPerRun: 90,
      frequencyPerWeek: 2,
      roiTimeSavedMinutesPerWeek: 150,
      roiDollarsPerMonth: 750,
    },
    {
      title: "Invoice Processing Automation",
      description: "Automatically extract, validate, and process invoices from suppliers with minimal manual intervention.",
      industryVertical: "Finance",
      scope: "Operations",
      department: "Accounts Payable",
      level: 3,
      goals: ["Cost Savings", "Efficiency", "Compliance"],
      riskRating: "Medium" as const,
      piiFlag: false,
      dataFlow: "CloudLLM" as const,
      humanInLoop: "Required" as const,
      storyToday: "Staff manually enters invoice data, matches to POs, and routes for approval - prone to errors and delays.",
      storyFuture: "1. AI extracts data from invoice PDFs\n2. Automatic PO matching\n3. Discrepancies flagged for review\n4. Approval routing based on amount\n5. Integration with accounting system",
      controls: ["Human review for amounts over threshold", "Duplicate detection", "Audit trail", "Vendor verification"],
      tools: ["OCR Software", "Accounting System", "Approval Workflow"],
      baselineMinutesPerRun: 20,
      frequencyPerWeek: 50,
      roiTimeSavedMinutesPerWeek: 800,
      roiDollarsPerMonth: 4000,
    },
    {
      title: "Customer Inquiry Email Responder",
      description: "AI-powered email triage and response drafting for common customer inquiries.",
      industryVertical: "Retail",
      scope: "Email Marketing",
      department: "Customer Service",
      level: 3,
      goals: ["Efficiency", "Customer Retention", "Cost Savings"],
      riskRating: "Low" as const,
      piiFlag: true,
      dataFlow: "CloudLLM" as const,
      humanInLoop: "Required" as const,
      storyToday: "Customer service reps manually read, categorize, and respond to each email - often with repetitive answers.",
      storyFuture: "1. AI categorizes incoming emails\n2. Draft responses generated for common queries\n3. Staff reviews and personalizes responses\n4. Complex issues escalated to specialists\n5. Response templates continuously improved",
      controls: ["Human approval before sending", "Sentiment analysis for escalation", "PII protection", "Response quality monitoring"],
      tools: ["Gmail/Outlook", "ChatGPT API", "CRM System"],
      baselineMinutesPerRun: 10,
      frequencyPerWeek: 100,
      roiTimeSavedMinutesPerWeek: 600,
      roiDollarsPerMonth: 3000,
    },
    {
      title: "Patient Intake Form Digitization",
      description: "Convert paper-based patient intake to digital forms with automatic data entry into practice systems.",
      industryVertical: "Podiatry",
      scope: "Operations",
      department: "Front Desk",
      level: 1,
      goals: ["Efficiency", "Compliance", "Cost Savings"],
      riskRating: "High" as const,
      piiFlag: true,
      dataFlow: "LocalOnly" as const,
      humanInLoop: "Required" as const,
      storyToday: "Patients fill paper forms in waiting room. Staff manually enters data into systems, taking 15 minutes per patient.",
      storyFuture: "1. Patient receives digital form link before visit\n2. Form completed online with validation\n3. Staff reviews for accuracy\n4. Approved data syncs to PMS\n5. Digital consent signatures captured",
      controls: ["HIPAA-compliant storage", "Data encryption", "Staff verification", "Consent tracking", "Audit logs"],
      tools: ["JotForm", "Practice Management System"],
      baselineMinutesPerRun: 15,
      frequencyPerWeek: 20,
      roiTimeSavedMinutesPerWeek: 240,
      roiDollarsPerMonth: 1200,
    },
    {
      title: "Inventory Reorder Alerts",
      description: "Automated monitoring and alerts when inventory levels fall below reorder thresholds.",
      industryVertical: "Retail",
      scope: "Operations",
      department: "Operations",
      level: 2,
      goals: ["Efficiency", "Cost Savings", "Revenue Growth"],
      riskRating: "Low" as const,
      piiFlag: false,
      dataFlow: "VendorTools" as const,
      humanInLoop: "Optional" as const,
      storyToday: "Staff manually checks inventory levels weekly and creates purchase orders, often missing low-stock items.",
      storyFuture: "1. System monitors inventory in real-time\n2. Low stock triggers alerts\n3. Reorder recommendations generated\n4. Staff approves or adjusts orders\n5. POs sent to suppliers automatically",
      controls: ["Budget limits", "Preferred vendor rules", "Approval thresholds", "Historical demand analysis"],
      tools: ["Inventory System", "Slack/Email", "Supplier Portal"],
      baselineMinutesPerRun: 60,
      frequencyPerWeek: 3,
      roiTimeSavedMinutesPerWeek: 150,
      roiDollarsPerMonth: 750,
    },
    {
      title: "Meeting Notes and Action Items",
      description: "AI-powered transcription and extraction of action items from team meetings.",
      industryVertical: "Professional Services",
      scope: "Communications",
      department: "All Teams",
      level: 3,
      goals: ["Efficiency", "Compliance", "Education"],
      riskRating: "Medium" as const,
      piiFlag: false,
      dataFlow: "CloudLLM" as const,
      humanInLoop: "Optional" as const,
      storyToday: "Someone takes manual notes during meetings. Action items often get lost. No searchable record of decisions.",
      storyFuture: "1. Meeting recorded and transcribed\n2. AI extracts key decisions and action items\n3. Summary distributed to attendees\n4. Action items assigned with due dates\n5. Follow-up reminders sent automatically",
      controls: ["Recording consent required", "Confidential meeting handling", "Retention policies", "Access controls"],
      tools: ["Zoom/Teams", "Otter.ai", "Slack", "Task Manager"],
      baselineMinutesPerRun: 30,
      frequencyPerWeek: 10,
      roiTimeSavedMinutesPerWeek: 200,
      roiDollarsPerMonth: 1000,
    },
    {
      title: "Lead Qualification Chatbot",
      description: "Conversational AI to qualify website leads 24/7 and route hot prospects to sales.",
      industryVertical: "B2B Services",
      scope: "Social",
      department: "Sales",
      level: 3,
      goals: ["Leads", "Revenue Growth", "Efficiency"],
      riskRating: "Low" as const,
      piiFlag: true,
      dataFlow: "CloudLLM" as const,
      humanInLoop: "Required" as const,
      storyToday: "Website visitors fill contact forms. Sales reps manually qualify leads, many go cold before follow-up.",
      storyFuture: "1. Chatbot engages visitors in conversation\n2. Qualifying questions asked naturally\n3. Hot leads get instant meeting booking\n4. Warm leads added to nurture sequence\n5. Sales notified of high-priority prospects",
      controls: ["Human handoff for complex questions", "Data privacy notices", "Bot disclosure", "CRM integration"],
      tools: ["Intercom/Drift", "ChatGPT", "Calendly", "CRM"],
      baselineMinutesPerRun: 15,
      frequencyPerWeek: 30,
      roiTimeSavedMinutesPerWeek: 360,
      roiDollarsPerMonth: 1800,
    },
  ];

  for (const template of marketplaceTemplates) {
    await db.insert(marketplaceUseCases).values(template);
    console.log("Created marketplace template:", template.title);
  }

  console.log("\nSeeding complete!");
};

seedData()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("Seeding failed:", error);
    process.exit(1);
  });
